### PR TITLE
fix: Score Dial appropriately closes

### LINKED ISSUE #81: Styled Popper does not disappear on the corners.
**Describe the bug**
Expected ScorePie component  to disappear when a score is selected or when a user moves their mouse outside of the circular dial.
When a use moves their mouse in a X pattern centered on the ScorePie the dial doesnt close when the user exits for the "corners".

**To Reproduce**
1. Go to a node
2. Click on Scoring number
3. Move mouse to 1 of the 4 corners of the bounding viewing box
4. Expected the ScorePie to disappear.

**Expected behavior**
- When a mouse is leaving the circle of the ScorePie, I expect it to disappear when mouse leaves the edge from every angle.

**Screenshots**
Expected: 
- bounding box for the mouse leave event.
- image

Actual:
- bounding box for the mouse leave event
- image

**Additional context**
- The component uses [react-minimal-pie-chart](https://www.npmjs.com/package/react-minimal-pie-chart)
- The ScorePie has a viewing-box that is larger then the pie menu. 
- The mouse leave events fire for the whole bounding box of the component for the react-minimal-pie-chart.
   - Assumption is that the inner pie shards extend to the viewing box for the mouse leave event handler.
- The mouse leave event is actually a square.

**Technical ideas**
- Change the <Box> component to a CIRCLE that matches the inside radius circle of the react-minimal-pie-chart,
- Center the react-minimal-pie-chart within the <CircleBox> and move mouse leave events to it.

### PR DESCRIPTION
**Pull request by Nezzely**
Closes #81

### Description of changes

- Added functionality to segment mouse events,handles mouseleave and mouse hover events.
- Applies CSS to currently hovered segment.
- Selection wheel closes as soon as mouse leaves the pie chart.

### CODE REVIEW

File: web/src/modules/topic/components/Score/ScorePie.tsx [hunk 1]
```diff
@@ -30,28 +43,33 @@ export const ScorePie = ({ pieDiameter, arguableId, arguableType }: Props) => {
...
       <PieChart
         data={data}
-        radius={50} // is relative to viewbox size [100, 100]
+        radius={45} // is relative to viewbox size [100, 100]
         label={({ dataEntry }) => dataEntry.key}
         labelStyle={() => ({
           fontSize: "14", // is relative to viewbox size [100, 100]
           pointerEvents: "none",
+          webKitUserSelect: "none" /* Safari */,
+          msUserSelect: "none" /* IE 10 and IE 11 */,
```
Comment (keyserj) [inline web/src/modules/topic/components/Score/ScorePie.tsx:55]: yooooo idk, mozilla doesn't even show IE in their browser compatibility list anymore, which makes me think it's not worth supporting (we'd have to go elsewhere for compatibility docs i guess?). what do you think?

File: web/src/modules/topic/components/Score/ScorePie.tsx [hunk 2]
```diff
@@ -30,28 +43,33 @@ export const ScorePie = ({ pieDiameter, arguableId, arguableType }: Props) => {
...
+    <StyledBox display="flex" width={pieDiameter} height={pieDiameter}>
       <PieChart
         data={data}
-        radius={50} // is relative to viewbox size [100, 100]
+        radius={45} // is relative to viewbox size [100, 100]
         label={({ dataEntry }) => dataEntry.key}
         labelStyle={() => ({
           fontSize: "14", // is relative to viewbox size [100, 100]
           pointerEvents: "none",
+          webKitUserSelect: "none" /* Safari */,
```
Comment (keyserj) [inline web/src/modules/topic/components/Score/ScorePie.tsx:54]: hmm I'm looking at the css in the browser and I don't see the webkit css prefix. not sure what the issue is here, BUT our styling solution (emotion) actually automatically adds prefixes - it [uses stylis by default](https://emotion.sh/docs/@emotion/cache#stylisplugins) and you can check out what should be generated by typing css into stylis's [homepage](https://stylis.js.org/). in this case, i think you should be able to do something like
```
labelStyle={() => css({ [insert css here] ... })
```
and it should add the prefixes (see emotion docs for [css object styling](https://emotion.sh/docs/object-styles#with-css))

File: web/src/modules/topic/components/Score/ScorePie.tsx [hunk 3]
```diff
@@ -30,28 +43,33 @@ export const ScorePie = ({ pieDiameter, arguableId, arguableType }: Props) => {
...
+          msUserSelect: "none" /* IE 10 and IE 11 */,
+          userSelect: "none" /* Standard syntax */,
         })}
         segmentsStyle={{
+          transformOrigin: "center",
```
Comment (keyserj) [inline web/src/modules/topic/components/Score/ScorePie.tsx:59]: was this necessary? mozilla says this is default https://developer.mozilla.org/en-US/docs/Web/CSS/transform-origin

File: web/src/modules/topic/components/Score/ScorePie.tsx [hunk 4]
```diff
@@ -30,28 +43,33 @@ export const ScorePie = ({ pieDiameter, arguableId, arguableType }: Props) => {
...
           transition: theme.transitions.create("all", {
             duration: theme.transitions.duration.shortest,
           }),
+          pointerEvents: "visiblePainted",
```
Comment (keyserj) [inline web/src/modules/topic/components/Score/ScorePie.tsx:63]: do you know if `visiblePainted` does anything special over `auto`? from a brief glance https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events it looks like they should behave the same for SVGs - and if that's the case, I'd just use `auto` here since that's equivalent to having no pointer-events property specified

**Review by keyserj — COMMENTED** [review]
bunch of NP's - nice work figuring out that pointer-event jazz

File: web/src/modules/topic/components/Score/ScorePie.tsx [hunk 5]
```diff
@@ -30,28 +43,33 @@ export const ScorePie = ({ pieDiameter, arguableId, arguableType }: Props) => {
...
         data={data}
-        radius={50} // is relative to viewbox size [100, 100]
+        radius={45} // is relative to viewbox size [100, 100]
         label={({ dataEntry }) => dataEntry.key}
         labelStyle={() => ({
           fontSize: "14", // is relative to viewbox size [100, 100]
           pointerEvents: "none",
+          webKitUserSelect: "none" /* Safari */,
+          msUserSelect: "none" /* IE 10 and IE 11 */,
+          userSelect: "none" /* Standard syntax */,
```
[the remark this answers is not in the document]
Comment (Nezzely) [reply web/src/modules/topic/components/Score/ScorePie.tsx:56]: The label was always selectable, i just didn't think a user ever wanted to copy the text

File: web/src/modules/topic/components/Score/ScorePie.tsx (hunk 1 above)
Comment (Nezzely) [reply web/src/modules/topic/components/Score/ScorePie.tsx:55]: Its a habit for me to put other browser CSS along with the default. I can remove it if you want! (I have no preference)

File: web/src/modules/topic/components/Score/ScorePie.tsx (hunk 4 above)
Comment (Nezzely) [reply web/src/modules/topic/components/Score/ScorePie.tsx:63]: `pointerEvents: "auto"` will work just fine.

File: web/src/modules/topic/components/Score/ScorePie.tsx (hunk 2 above)
Comment (Nezzely) [reply web/src/modules/topic/components/Score/ScorePie.tsx:54]: Nice call out! i wasn't familiar with the syntax `labelStyle={() => css({ [insert css here] ... })`
works like a charm <3
`transform: dataIndex === hovered ? "scale(1.1)" : "",`

File: web/src/modules/topic/components/Score/ScorePie.tsx [hunk 6]
```diff
@@ -18,6 +19,18 @@ export const ScorePie = ({ pieDiameter, arguableId, arguableType }: Props) => {
   const theme = useTheme();
   const [hovered, setHovered] = useState<number | undefined>(undefined);
 
+  const segmentMouseEvent = (event: React.MouseEvent, index: number | undefined) => {
+    const target = event.target as HTMLElement;
+    if (index === undefined) {
```
[the remark this answers is not in the document]
Comment (Nezzely) [reply web/src/modules/topic/components/Score/ScorePie.tsx]: function removed in favor of segmentStyling

**Review by keyserj — APPROVED** [review]
steph-curry-halfcourt-shot
